### ISSUE TITLE
HGETALL returns array instead of hash

### ISSUE THREAD

**Issue by raphaottoni** [codekitchen/redis-rb-scripting#2]
Acessing the key from redis-rb gem using hgetall return a hash:

![screen shot 2015-06-18 at 23 59 44](https://cloud.githubusercontent.com/assets/5016450/8246768/5c77ffd8-161a-11e5-9ea6-a9f71dde0862.png)

when accessing the same key with a lua script using redis-rb-scripting it returns a array:
![screen shot 2015-06-19 at 00 31 34](https://cloud.githubusercontent.com/assets/5016450/8246782/9dee246a-161a-11e5-9cc4-7a970081341b.png)

hmget.lua
![screen shot 2015-06-18 at 23 57 37](https://cloud.githubusercontent.com/assets/5016450/8246772/6181d8dc-161a-11e5-8349-49832f1f3ec3.png)

Same problem occur with wolverine gem: 
https://github.com/Shopify/wolverine/issues/13

**Comment by codekitchen** [comment]
This is because the redis-rb gem does special processing on the return value of `hgetall`, you can see how the return value is processed through the `_hashify` method before returning https://github.com/redis/redis-rb/blob/master/lib/redis.rb#L2013

You can see the same behavior without this gem, just calling `eval` on the redis connection directly. You'll just need to do the processing yourself when doing it via a lua script.
